# Default values for api-getway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 937399771982.dkr.ecr.us-west-1.amazonaws.com/api-getway
  tag: v9.0.0.3-dev
  pullPolicy: Always

arg: "server"

env:
  USER_SERVICE: user-server:7000
  IMAGE_SERVICE: image-server:7000
  MOMENT_SERVICE: moment-server:7000
  FILTER_WORD_SERVICE: filter-word:7000
  PURCHASE_SERVICE: purchase-server:7000
  CARDS_SERVICE: cards-server:7000
  VALENTINES_DAY_SERVER: valentines-day-server:7000

  HBASE_HOST: hbase-adapter-2:7000

  #用户活跃事件的采样率%
  ACTIVE_SAMPLING: 100
  #jwt过期时间7d=604800s. 0表示不过期
  AUTH_TOKEN_EXPIRE_SEC: 0
  AUTH_RENEW_EXPIRE_SEC: 3660
  AUTH_RENEW_INTERVAL_SEC: 540
  WOOPLUS_NAME: WooPlus
  PAGE_SIZE: 20
  BUCKET: wooplus-stage-img
  CLIENT_LOG_BUCKET: wooplus-stage-client-log
  BUCKET_REGION: ap-southeast-1
  MESSAGE_BUCKET: message-log-dev
  VOICE_BUCKET: ttt-dev-voice
  IMAGE_TRASH_BUCKET: ttt-dev-image-trash
  VIDEO_BUCKET: wooplus-video-stage
  IM_HISTORY_BUCKET: wooplus-im-history-stages
  MESSAGE_ROUTE_THRESHOLD: 5
  RESET_PASSWORD_EMAIL_TIMES: 2
  RESET_PASSWORD_EMAIL_EXPIRE: 3
  VERIFY_EMAIL_QUOTA: 10
  #单位分钟
  VERIFY_EMAIL_QUOTA_DURATION: 5
  UPLOAD_IMAGE_FORMAT: image/jpeg,image/png,image/vnd.sealedmedia.softseal-jpg,image/jpg,image/webp
  LINKV_TOKEN_COUNT: 10
  MONITOR_PUSH_URL: http://prometheus-pushgateway.istio-system.svc.cluster.local:9091
  MONITOR_PUSH_TIMEOUT_MILLISECOND: 100
  MONITOR_PUSH_INTERVAL_SECOND: 58
  MIN_APP_BUILD_OF_SUPPORT: 70304
  REGISTER_LIMIT_SECOND: 10
  AVAILABLE_REMOTE_CONFIG_KEYS: "sayhi_follow_wooplus_fb"
  BOOST_CACHE_SECOND: 60
  VIDEO_BASE_URL: https://video-stage2.apiteamn.com/

  SMS_VERIFY_IP_LIMIT_RPM: 2
  SMS_VERIFY_IP_LIMIT_RPT: 4
  SMS_VERIFY_IP_LIMIT_RPD: 0
  #https://yumingsuoxie.bmcx.com/
  #https://en.wikipedia.org/wiki/List_of_country_calling_codes
  SMS_BLOCK_REGIONS: "+92,+880,+266,+221,+227,+218,+998"
  SMS_WHITE_REGIONS: "+1,+63,+44,+98,+971,+61,+1,+86,+49,+7,+31,+95,+966,+91,+255,+33,+90,+225,+55,+20,+961,+357,+34,+256,+58,+251,+212,+962,+856,+53,+358"
  PUSH_TASK_IP_LIMIT_RPM: 5

  AWS_REGION: "ap-east-1"                         #aws区域
  AWS_RELATIONSHIP_BUCKET: "relationship-stage"   #s3存储桶

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: { }
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
# 
resources: { }
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
#  cpu: 100m
#  memory: 128Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }
